services:
  yt-dlp:
    image: python
    restart: always
    build: ./yt-dlp/
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - app-network

  next:
    build: .
    restart: always
    expose:
      - 3000
    depends_on:
      - cloudflared
      - yt-dlp
    links:
      - yt-dlp
    env_file:
      - .env
    environment:
      - NODE_ENV=${ENVIRONMENT}
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: .env
        - action: rebuild
          path: instrimentation.ts

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
      - TUNNEL_URL=http://next:3000
    restart: unless-stopped
    networks:
      - app-network

volumes:
networks:
  app-network:
    driver: bridge
