services:
  yt-dlp:
    image: python
    restart: always
    build: ./yt-dlp/
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - app-network

  next:
    build: .
    restart: always
    expose:
      - 3000
    depends_on:
      - redis
      - cloudflared
      - yt-dlp
    links:
      - redis
      - yt-dlp
    env_file:
      - .env
    environment:
      - NODE_ENV=${ENVIRONMENT}
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
      - TUNNEL_URL=http://next:3000
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis:
    driver: local

networks:
  app-network:
    driver: bridge
